image:
  repository: quay.io/globex-sentiment-analysis/sentiment-analysis-moderate-reviews
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""

podAnnotations:
  autoscaling.knative.dev/min-scale: '1'

resources:
  limits:
    memory: 6000Mi
  requests:
    memory: 1000Mi

gunicorn:
  threads: "4"
  timeout: "180"

cloudEvents:
  source: review-moderated
  type: review-moderated-event
