nameOverride: serverless-kafka-secret

image:
  repository: quay.io/cloud-architecture-workshop/serverless-kafka-secret-job
  pullPolicy: IfNotPresent
  tag: "a0b7696"
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

secret: kafka-secret  

kafka:
  namespace: 

argocd:
  enabled: true
  syncwave: "-2"