apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kafka-secret.name" . }}
  labels:
    {{- include "kafka-secret.labels" . | nindent 4 }}
  annotations:
    {{- include "kafka-secret.argocd-syncwave" . | nindent 4 }}
spec:
  selector: {}
  template:
    metadata:
      name: {{ include "kafka-secret.name" . }}
    spec:
      serviceAccountName: {{ include "kafka-secret.name" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_NAMESPACE
              value: {{ .Values.kafka.namespace }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLIENT_SECRET
              value: {{ .Values.secret }}
      restartPolicy: Never