apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kafka-secret.name" . }}
  labels:
    {{- include "kafka-secret.labels" . | nindent 4 }}
  annotations:
    {{- include "kafka-secret.argocd-syncwave" . | nindent 4 }}
  namespace: {{ .Values.kafka.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "kafka-secret.name" . }}
  namespace: {{ .Release.Namespace }}