apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-secret.name" . }}
  labels:
    {{- include "kafka-secret.labels" . | nindent 4 }}
  annotations:
    {{- include "kafka-secret.argocd-syncwave" . | nindent 4 }}