apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aiml-moderate-reviews.name" . }}
  labels:
    {{- include "aiml-moderate-reviews.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  TRANSFORMERS_CACHE: /app/cache
  moderated_reviews_sink: {{ .Values.kafkaSink.moderated }}
  denied_reviews_sink: {{ .Values.kafkaSink.denied }}
  ce_type: {{ .Values.cloudEvents.type }}
  ce_source: {{ .Values.cloudEvents.source }}
