apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "products-review.name" . }}
  labels:
    {{- include "products-review.labels" . | nindent 4 }}
    app.openshift.io/runtime: quarkus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "products-review.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "products-review.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "products-review.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /deployments/config
              name: config
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: cloudevents.ce-source
              value: {{ .Values.cloudEvents.source }}
            - name: cloudevents.ce-type
              value: {{ .Values.cloudEvents.type }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "products-review.name" . }}
