sinkbinding:
  - name: product-reviews-to-reviews-sink
    sink:
      ref:
        apiVersion: eventing.knative.dev/v1alpha1
        kind: KafkaSink
        name: reviews-sink
    subject:
      apiVersion: apps/v1
      kind: Deployment
      name: product-reviews
  - name: aiml-sentiment-reviews-to-reviews-sentiment-sink
    sink:
      ref:
        apiVersion: eventing.knative.dev/v1alpha1
        kind: KafkaSink
        name: reviews-sentiment-sink
    subject:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: aiml-sentiment-reviews
  - name: aiml-moderate-reviews-to-moderated-reviews-sink
    sink:
      ref:
        apiVersion: eventing.knative.dev/v1alpha1
        kind: KafkaSink
        name: moderated-reviews-sink
    subject:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: aiml-moderate-reviews
